name: CD GraphQL

on: [push]

jobs:
  deploy:
      runs-on: ubuntu-latest
      strategy:
        fail-fast: true
        matrix:
          node-version: [18.x]

      steps:
        - name: deploy GraphQL to server
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            port: ${{ secrets.PORT }}
            script: pm2 stop index
              cd /var/www/html/planifecation
              git pull
              npx prisma migrate dev --name "migrationA"
              pm2 start
            
