name: CD GraphQL

on:
  push:
    branches:
      - dev
    paths:
      - 'Serveur/**'
  pull_request:
    branches:
      - dev
    paths:
      - 'Serveur/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: [18.x]

    steps:
      - name: Deploy GraphQL to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            # Arrêter le processus PM2
            pm2 stop index

            # Naviguer au répertoire du projet
            cd /var/www/html/planifecation/Serveur

            # Mettre à jour le code source
            git pull origin dev

            # Installer les dépendances
            yarn install --production=false

            # Appliquer les migrations de base de données
            npx prisma migrate reset --force

            # Redémarrer l'application via PM2
            pm2 start index
