name: CD GraphQL

on:
  push:
    branches:
      - dev
      - 52-je-veux-que-ma-cd-de-serveur-ne-se-déclenche-que-lorsquil-y-a-des-modifications-dans-ce-dossier
#    paths:
#      - 'Serveur/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Récupère l'historique complet pour les migrations

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile  # Assurez-vous que yarn.lock est commité

      - name: Apply Database Migrations
        run: npx prisma reset --force

      - name: Deploy GraphQL to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            pm2 stop index
            cd /var/www/html/planifecation/Serveur
            git pull origin dev
            yarn install --production=false
            pm2 start index

