name: CD GraphQL

on:
  push:
    branches:
      - dev
    paths:
      - 'Serveur/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: [18.x]

    steps:
      - name: Deploy GraphQL to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            pm2 stop index
            cd /var/www/html/planifecation/Serveur
            git pull origin dev
            yarn install --production=false
            npx prisma migrate dev --name "${{github.run_id}}"
            npx prisma migrate reset --force
            pm2 start index
