name: Prettier Check 

jobs:
  prettier-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16  # Changez la version de Node.js si nécessaire

      - name: Install Dependencies
        run: npm install

      - name: Prettier Check
        run: |
          cd Application
          npm run prettier-check
