name: Run Tests

on:
  pull_request:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: alpine:3.19.1

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # Ou la version de Node.js que vous utilisez

      - name: Install Dependencies
        run: |
          cd Application
          yarn install

      - name: Run Tests
        run: |
          cd Application
          yarn test
